# 图片验证码有效时间
IMAGE_CODE_REDIS_EXPIRES = 5 * 60

# 验证码有效时间
SMS_CODE_REDIS_EXPIRES = 5 * 60

# 发送间隔
SEND_SMS_CODE_INTERVAL = 60

SMS_CODE_TEMP_ID = 1

# 验证邮件token过期时间
VERIFY_EMAIL_TOKEN_EXPIRES = 15 * 60

# 用户地址保存最大值
USER_ADDRESS_COUNTS_LIMIT = 5
